sudo: false
language: python
python: 2.7
env:
  global:
    PIP_INDEX_URL=https://storax.github.io/travis-pyside-test/simple/
    PIP_EXTRA_INDEX_URL=https://pypi.python.org/simple
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - TOXENV=check
{% for env, config in tox_environments|dictsort %}
    - TOXENV={{ env }}{% if config.cover %},coveralls{% endif %}

{% endfor %}
addons:
  apt:
    packages:
    - xvfb
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
script:
  - Xvfb :0 -screen 0 1600x1200x24 &
  - export DISPLAY=:0.0
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: never
